services:
  - type: worker
    name: drainer
    runtime: rust
    plan: standard
    autoDeploy: true
    buildCommand:  cargo build --release
    startCommand: cargo run --release
    envVars:
      - fromGroup: drainer
